CREATE TABLE "GCG_5486_MAINT"(
 "SUNDAY" BIT NOT NULL ,
 "MONDAY" BIT NOT NULL ,
 "TUESDAY" BIT NOT NULL ,
 "WEDNESDAY" BIT NOT NULL ,
 "THURSDAY" BIT NOT NULL ,
 "FRIDAY" BIT NOT NULL ,
 "SATURDAY" BIT NOT NULL ,
 "REDMIN" INTEGER NOT NULL ,
 "GREENMAX" INTEGER NOT NULL );